######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 8 20:30:42 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT -= gui
QT += network

# Input
SOURCES += main.cpp
